#SurvivalGames config file
language: English

#Set how many players are needed for the game
#to auto-start. Once the player limit is reached
#it will wait for x amount of seconds for
#additional players. Auto start vote means that
#x percent of players need to vote with /sg vote
#for the game to begin
auto-start-players: 20
auto-start-time: 20
auto-start-vote: 75

#If the player queue is enabled then if a player
#tries to join a game that is not joinable
#(ie ingame) the player will be added to a
#queue line to join the next time the game
#is open
enable-player-queue: true

#Set how long the grace period for be after the start of
#the game in seconds.
grace-period: 20

#Here you can control block placing and breaking.
block:
  place:
    whitelist:
    - 18
    - 105
    - 31
    - 37
    - 38
    - 50
    - 103
    - 43
  break:
    whitelist:
    - 18
    - 105
    - 31
    - 37
    - 38
    - 50
    - 103
    - 43

#Settings for when the game nears end. This runs
#when there are only x amount of players
#remaining. If place chest is enabled then
#when the player limit is reached, a chest
#will be placed inside the radius of every
#remain player containing random items for
#that player. If fire-lighting is enabled
#then a lighting strike will be fired at the
#location of each player every x seconds to
#notify the other players of their location
endgame:
  players: 3
  fire-lighting:
    enabled: true
    interval: 20

#If enabled, after x amount of time, each player
#remaing will be teleported to the center of the
#arena for a death match. If they have not been
#killed after killtime, the game will end.
deathmatch:
  enabled: false
  time: 30
  killtime: 5

#Enable game stats
stats: "true"
#set stats provider (yaml, sql, mysql)
stats_provider: yaml