#Arena name:
name: "default"

#Arena level
world: "world"

#Arena area
area_pos1:
  x:
  y:
  z:

area_pos2:
  x:
  y:
  z:

sign:
  join_sign:
    x: 20
    y: 15
    z: 316
    world: "world"
  #allow game status on the join sign
  allow_status: "true"
  #you can use these variables: %name - arena name, %maxplayers, $minplayers, %aliveplayers, %map - game map, %phase - game phase like deathmatch/waiting
  status_line_1: ""
  status_line_2: ""
  status_line_3: ""
  status_line_4: ""

#leave position (when player die or leave)
leave_position:
  x: 34
  y: 48
  z: -987
  world: "world"

#Write spawn positions:
spawn_positions:
-  x: 24
   y: 10
   z: 498
-  x: 29
   y: 10
   z: 490
-  x: 35
   y: 10
-  z: 459

#arena world time   night/day/cycle or type time in ticks
time: "cycle"